on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
      # Step 2: Decode Google services configuration file
    - name: Decode google-services.json
      env:
        FIREBASE_ANDROID_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: echo $FIREBASE_ANDROID_CONFIG > beer_penalty/android/app/google-services.json
    - uses: subosito/flutter-action@v1
    - name: Get dependencies
      run: flutter pub get
      working-directory: ./beer_penalty      
    - name: Run tests
      run: flutter test
      working-directory: ./beer_penalty      
    - name: Build APK
      run: flutter build apk --debug --split-per-abi
      working-directory: ./beer_penalty
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "beer_penalty/build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}